#!/bin/bash

if [[ $1 = "-h" ]]; then
  echo "
  moonbian ports tree fetcher script
  Licensed under WTFPL license || (!C) 2016 moondeck

  All rights unreserved
  I am not responsible for any failtures of this program

  usage: just run this script to fetch the port tree, nothing more, nothing less
  Then go to /usr/local/ports and install whatever you need
  "
  exit
fi

cd /usr/local
mkdir ports
cd ports

wget http://repo.novakovsky.eu/ports/*.tar.gz

if [[ ! ($? == 1) ]]; then
  echo "*** COULDNT FETCH PORTS - ABORTING ***"
  exit
fi


tar -xf *.tar.gz

date > fetchdate

md5sum -c checklist.md5

if [[ ! ($? == 0) ]]; then
  echo "*** BAD CHECKSUM - ABORTING ***"
  exit
fi
